repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: uv run black
        language: system
        args: ["-l", "120", "--check"]
        types: [python]
        
      - id: ruff
        name: ruff
        entry: uv run ruff
        language: system
        args: ["check"]
        types: [python]
        
      - id: django-check-migrations
        name: check for missing migrations
        entry: uv run python manage.py makemigrations
        language: system
        args: ["--check", "--dry-run"]
        files: "models\\.py$"
        pass_filenames: false